<section class="mt-3 card card-body">
    <h1>Gerenciar Cursos</h1>

    <div class="mt-2">
        <a href="/cursos/novo" class="btn btn-outline-dark">Novo Curso</a>

        <a href="/cursos/relatorio" class="btn btn-outline-dark">Gerar PDF</a>
    </div>

    <table class="table table-striped table-hover mt-4">
        <thead class="table-dark">
            <tr>
                <th>#ID</th>
                <th>Nome</th>
                <th>Categoria</th>
                <th>Ações</th>
            </tr>
        </thead>
        <tbody>
            <?php
            
            if (isset($cursos) && sizeOf($cursos) > 0) {
                foreach ($cursos as $curso) {
                    echo "
                            <tr>
                                <td>{$curso['curso_id']}</td>
                                <td>{$curso['curso_nome']}</td>
                                <td>{$curso['categoria_nome']}</td>
                                <td>
                                <a href='/cursos/editar?id={$curso['curso_id']}' class='btn btn-outline-warning'>Editar</a>
                                <button type='button' class='btn btn-outline-danger' data-bs-toggle='modal' data-bs-target='#staticBackdrop'>
                                    Excluir
                                </button>
                                <div class='modal fade' id='staticBackdrop' data-bs-backdrop='static' data-bs-keyboard='false' tabindex='-1' aria-labelledby='staticBackdropLabel' aria-hidden='true'>
                                    <div class='modal-dialog'>
                                        <div class='modal-content'>
                                        <div class='modal-header'>
                                            <h1 class='modal-title fs-5' id='staticBackdropLabel'>EXCLUIR</h1>
                                            <button type='button' class='btn-close' data-bs-dismiss='modal' aria-label='Close'></button>
                                        </div>
                                        <div class='modal-body'>
                                            Você quer mesmo excluir?
                                        <div class='modal-footer'>
                                            <button type='button' class='btn btn-secondary' data-bs-dismiss='modal'>Não</button>
                                            <a href='/cursos/excluir?id={$curso['curso_id']}' class='btn btn-danger'>Sim</a>
                                        </div>
                                        </div>
                                    </div>
                                    </div>
                                </td>
                            </tr>
                        ";
                }
            }
            ?>
        </tbody>
    </table>
</section>

<!-- Modal -->
<div class='modal fade' id='staticBackdrop' data-bs-backdrop='static' data-bs-keyboard='false' tabindex='-1' aria-labelledby='staticBackdropLabel' aria-hidden='true'>
    <div class='modal-dialog'>
        <div class='modal-content'>
            <div class='modal-header'>
                <h1 class='modal-title fs-5' id='staticBackdropLabel'>Excluir</h1>
                <button type='button' class='btn-close' data-bs-dismiss='modal' aria-label='Close'></button>
            </div>
            <div class='modal-body'>
                Você quer Excluir?
            </div>
            <div class='modal-footer'>
                <button type='button' class='btn btn-secondary' data-bs-dismiss='modal'>Não</button>
                <button type='button' class='btn btn-primary'>Sim</button>
            </div>
        </div>
    </div>
</div>

<!-- JavaScript Bundle with Popper -->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+jjXkk+Q2h455rYXK/7HAuoJl+0I4" crossorigin="anonymous"></script>